name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pip install pylint
        pylint ./app --fail-under=8.5

    - name: Run tests
      run: |
        pip install pytest pytest-cov
        pytest -c pytest.ini --cov --cov-fail-under=85

        env:
          FLASK_ENV: ${{ secrets.FLASK_ENV }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag product-catalog-service:$(date +%s)
